# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp

pod 'MBProgressHUD', '~> 0.9.1'
pod 'ZXingObjC', '~> 3.0'
pod 'MistSDK', '~> 1.2.0'
end
